/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplier;
import admin.*;
import produk.*;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import javax.swing.table.DefaultTableModel;
import login.Dashboard;
import transaksi.TransaksiForm;

/**
 *
 * @author user
 */
public class SupplierForm extends javax.swing.JFrame {
    
    /**
     * Creates new form MainMenu
     */
    java.sql.Connection con = Koneksi.ConnectionDB();
    
    public SupplierForm() {
        initComponents();
        buka_tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kodeSupplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namaSupplier = new javax.swing.JTextField();
        teleponSupplier = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tableBarang = new javax.swing.JScrollPane();
        tabelSupplier = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        alamatSupplier = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnProduk = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("MenuFrame"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 80, 150));
        jLabel1.setText("SUPPLIER PRODUK");

        jLabel2.setText("KODE SUPPLIER");

        jLabel3.setText("NAMA SUPPLIER");

        teleponSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleponSupplierActionPerformed(evt);
            }
        });
        teleponSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teleponSupplierKeyTyped(evt);
            }
        });

        jLabel5.setText("TELEPON SUPPLIER");

        tabelSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KODE", "NAMA", "TELEPON", "ALAMAT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelSupplier.setRowHeight(30);
        tabelSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSupplierMouseClicked(evt);
            }
        });
        tableBarang.setViewportView(tabelSupplier);

        btnSimpan.setBackground(new java.awt.Color(15, 80, 150));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(200, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(70, 70, 70));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.setBorder(null);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel6.setText("ALAMAT SUPPLIER");

        jLabel4.setForeground(new java.awt.Color(200, 0, 0));
        jLabel4.setText("*Nomor Harus Berupa Angka 0-9");

        jLabel7.setForeground(new java.awt.Color(200, 0, 0));
        jLabel7.setText("*Kode Harus Diawali SUPP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(alamatSupplier)
                            .addComponent(kodeSupplier)
                            .addComponent(namaSupplier)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(teleponSupplier))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(tableBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teleponSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamatSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tableBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(15, 80, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(1126, 50));

        btnDashboard.setBackground(new java.awt.Color(20, 80, 160));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("DASHBOARD");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(20, 80, 160));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setText("ADMIN");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnProduk.setBackground(new java.awt.Color(20, 80, 160));
        btnProduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnProduk.setText("PRODUK");
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });

        btnSupplier.setBackground(new java.awt.Color(20, 80, 160));
        btnSupplier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplier.setText("SUPPLIER");
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(748, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        // Validasi Input
        if (!isValidString(kodeSupplier.getText())) {
            JOptionPane.showMessageDialog(null, "Kode Supplier tidak boleh kosong.");
            return;
        }
        if (!isValidString(namaSupplier.getText())) {
            JOptionPane.showMessageDialog(null, "Nama Supplier tidak boleh kosong.");
            return;
        }
        if (!isValidString(teleponSupplier.getText())) {
            JOptionPane.showMessageDialog(null, "Nomor Supplier harus berupa angka 0-9.");
            return;
        }
        if (!isValidString(alamatSupplier.getText())) {
            JOptionPane.showMessageDialog(null, "Alamat Supplier tidak boleh kosong.");
            return;
        }
        
        
        
        try {
            
            String sql = "INSERT INTO tb_supplier (kode_supplier, nama_supplier, telepon_supplier, alamat_supplier ) VALUES"
                    + "(?, ?, ?, ?)";
            
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, kodeSupplier.getText());
            pst.setString(2, namaSupplier.getText());
            pst.setString(3, teleponSupplier.getText());
            pst.setString(4, alamatSupplier.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Supplier Berhasil Disimpan");
            kodeSupplier.setText("");
            namaSupplier.setText("");
            teleponSupplier.setText("");
            alamatSupplier.setText("");

            // Set focus
            kodeSupplier.requestFocusInWindow();

            buka_tabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Menghapus ' " + namaSupplier.getText() + "'", " Konfirmasi Hapus ",
                JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                
                String sql = "DELETE FROM tb_supplier WHERE kode_supplier= '" + kodeSupplier.getText().trim() + " ' " ;
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Data Supplier Berhasil Dihapus");
                kodeSupplier.setText("");
                namaSupplier.setText("");
                teleponSupplier.setText("");
                alamatSupplier.setText("");
                kodeSupplier.enable();
                kodeSupplier.requestFocusInWindow();
                buka_tabel();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Proses hapus gagal/koneksi gagal .. ");
                System.out.println(e.getMessage());

            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSupplierMouseClicked
        kodeSupplier.disable();
        int row = tabelSupplier.getSelectedRow();
        kodeSupplier.setText(tabelSupplier.getModel().
                getValueAt(row, 0).toString());
        namaSupplier.setText(tabelSupplier.getModel().
                getValueAt(row, 1).toString());
        teleponSupplier.setText(tabelSupplier.getModel().
                getValueAt(row, 2).toString());
        alamatSupplier.setText(tabelSupplier.getModel().
                getValueAt(row, 3).toString());
        
    }//GEN-LAST:event_tabelSupplierMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        if (!isValidString(namaSupplier.getText())) {
            JOptionPane.showMessageDialog(null, "Nama Supplier tidak boleh kosong.");
            return;
        }
        if (!isValidString(teleponSupplier.getText())) {
            JOptionPane.showMessageDialog(null, "Nomor Supplier harus berupa angka 0-9.");
            return;
        }
        
        if (!isValidString(alamatSupplier.getText())) {
            JOptionPane.showMessageDialog(null, "Alamat Supplier tidak boleh kosong.");
            return;
        }
        try {
            
            String sql = "UPDATE tb_supplier SET "
                    + "nama_supplier=" + "'" + namaSupplier.getText() + "',"
                    + "telepon_supplier=" + "'" + teleponSupplier.getText() + "',"
                    + "alamat_supplier=" + "'" + alamatSupplier.getText() + "'"
                    + "WHERE kode_supplier=" + "'" + kodeSupplier.getText() + "';";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Data berhasil di Edit");
            namaSupplier.setText("");
            teleponSupplier.setText("");
            alamatSupplier.setText("");
            namaSupplier.setEnabled(true);
            namaSupplier.requestFocusInWindow();
            buka_tabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Proses edit gagal .. ");
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        Dashboard activityDashboard = new Dashboard();

        activityDashboard.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        AdminForm activityAdmin = new AdminForm();

        activityAdmin.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        ProdukForm activityProduk = new ProdukForm();

        activityProduk.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnProdukActionPerformed

    private void teleponSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleponSupplierActionPerformed
       
    }//GEN-LAST:event_teleponSupplierActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        SupplierForm activitySupplier = new SupplierForm();

        activitySupplier.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void teleponSupplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teleponSupplierKeyTyped
        char character= evt.getKeyChar();
        if(!Character.isDigit(character) || teleponSupplier.getText().length() >= 15){
            evt.consume();
        }
    }//GEN-LAST:event_teleponSupplierKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatSupplier;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kodeSupplier;
    private javax.swing.JTextField namaSupplier;
    private javax.swing.JTable tabelSupplier;
    private javax.swing.JScrollPane tableBarang;
    private javax.swing.JTextField teleponSupplier;
    // End of variables declaration//GEN-END:variables


    private void buka_tabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("KODE");
        model.addColumn("NAMA");
        model.addColumn("TELEPON");
        model.addColumn("ALAMAT");

        // menampilkan data kedalam table
        try {
            String sql = "SELECT kode_supplier, nama_supplier, telepon_supplier, alamat_supplier FROM tb_supplier";
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("kode_supplier"),
                    res.getString("nama_supplier"),
                    res.getString("telepon_supplier"),
                    res.getString("alamat_supplier")
                });
            }
            tabelSupplier.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private boolean isValidString(String input) {
        return input != null && !input.trim().isEmpty();
    }
    

    
    //end 

  
    }

