/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package produk;
import admin.AdminForm;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
import login.Dashboard;
import supplier.SupplierForm;

/**
 *
 * @author user
 */
    
public class ProdukForm extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    java.sql.Connection con = Koneksi.ConnectionDB();
    
    public ProdukForm() {
        initComponents();
        buka_tabel();
        comboBox();
        namaSuplierComboBox();
    }
    
    private void comboBox() {
        try {
           // Fungsi Untuk mengambil nilai enum pada database 
            String sql = "SHOW COLUMNS FROM tb_barang LIKE 'kategori_barang'";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            java.sql.ResultSet cek = pst.executeQuery();

            if (cek.next()) {
                String enumValue = cek.getString("Type");
                enumValue = enumValue.replace("enum(", "")
                        .replace(")", "").replace("'", "");

                String[] values = enumValue.split(",");

                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

                for (String value : values) {
                    model.addElement(value.trim());
                }
                kategoriBarang.setModel(model);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void namaSuplierComboBox() {
        try {
           // Implemntasi Relasi Database yang ditampilkan pada form PRoduk 
            String sql = "SELECT nama_supplier FROM tb_supplier ";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String namaSupplier = rs.getString("nama_supplier");
                supplierComboBox.addItem(namaSupplier);
            }

            rs.close();
            pst.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal mengambil data suplier: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namaBarang = new javax.swing.JTextField();
        jumlahBarang = new javax.swing.JTextField();
        hargaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kategoriBarang = new javax.swing.JComboBox<>();
        tableBarang = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        supplierComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnSupplier = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnAdmin1 = new javax.swing.JButton();
        btnProduk1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("MenuFrame"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 80, 150));
        jLabel1.setText("PRODUK SPAREPART");

        jLabel2.setText("NOMOR BARANG");

        jLabel3.setText("NAMA BARANG");

        jLabel4.setText("KATEGORI BARANG");

        jLabel5.setText("HARGA BARANG");

        jLabel6.setText("JUMLAH BARANG");

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO", "NAMA", "KATEGORI", "HARGA", "STOCK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelBarang.setRowHeight(30);
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        tableBarang.setViewportView(tabelBarang);

        btnSimpan.setBackground(new java.awt.Color(15, 80, 150));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(200, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(70, 70, 70));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.setBorder(null);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel7.setText("NAMA SUPPLIER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahBarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaBarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kategoriBarang, javax.swing.GroupLayout.Alignment.LEADING, 0, 282, Short.MAX_VALUE)
                            .addComponent(namaBarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idBarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addComponent(tableBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)
                        .addComponent(kategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tableBarang))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(15, 80, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(1126, 50));

        btnSupplier.setBackground(new java.awt.Color(20, 80, 160));
        btnSupplier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplier.setText("SUPPLIER");
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnDashboard.setBackground(new java.awt.Color(20, 80, 160));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("DASHBOARD");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnAdmin1.setBackground(new java.awt.Color(20, 80, 160));
        btnAdmin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdmin1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin1.setText("ADMIN");
        btnAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin1ActionPerformed(evt);
            }
        });

        btnProduk1.setBackground(new java.awt.Color(20, 80, 160));
        btnProduk1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProduk1.setForeground(new java.awt.Color(255, 255, 255));
        btnProduk1.setText("PRODUK");
        btnProduk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduk1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308)
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(880, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(btnAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1162, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(300, 300, 300)
                    .addComponent(btnProduk1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1019, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnAdmin1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnProduk1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        // Validasi Input
        if (!isValidInt(idBarang.getText())) {
            JOptionPane.showMessageDialog(null, "ID harus berupa angka.");
            return;
        }
        if (!isValidString(namaBarang.getText())) {
            JOptionPane.showMessageDialog(null, "Nama barang tidak boleh kosong.");
            return;
        }
        if (!isValidInt(hargaBarang.getText())) {
            JOptionPane.showMessageDialog(null, "Harga harus berupa angka.");
            return;
        }
        if (!isValidInt(jumlahBarang.getText())) {
            JOptionPane.showMessageDialog(null, "Stock harus berupa angka.");
            return;
        }
        
        
        try {
            
            String sql = "INSERT INTO tb_barang VALUES"
                    + "('" + idBarang.getText() + "',"
                    + "'" + supplierComboBox.getSelectedItem().toString() + "',"
                    + "'" + namaBarang.getText() + "',"
                    + "'" + kategoriBarang.getSelectedItem().toString() + "',"
                    + "'" + hargaBarang.getText() + "',"
                    + "'" + jumlahBarang.getText() + "')";
           
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Barang Berhasil Disimpan");
            idBarang.setText("");
            namaBarang.setText("");
            hargaBarang.setText("");
            jumlahBarang.setText("");

            // Set focus
            idBarang.requestFocusInWindow();

            buka_tabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Menghapus ' " + namaBarang.getText() + "'", " Konfirmasi Hapus ",
                JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
               
                String sql = "delete from tb_barang where "
                        + "id_barang= ' " + idBarang.getText() + "' ";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                idBarang.setText("");
                namaBarang.setText("");
                hargaBarang.setText("");
                jumlahBarang.setText("");
                idBarang.enable();
                idBarang.requestFocusInWindow();
                buka_tabel();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Proses hapus gagal/koneksi gagal .. ");
                System.out.println(e.getMessage());

            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        int row = tabelBarang.getSelectedRow();
        idBarang.setText(tabelBarang.getModel().
                getValueAt(row, 0).toString());
        namaBarang.setText(tabelBarang.getModel().
                getValueAt(row, 2).toString());
        hargaBarang.setText(tabelBarang.getModel().
                getValueAt(row, 4).toString());
        jumlahBarang.setText(tabelBarang.getModel().
                getValueAt(row, 5).toString());
        idBarang.disable();
        kategoriBarang.disable();
        supplierComboBox.disable();
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
            Dashboard activityDashboard = new Dashboard();

            activityDashboard.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
            SupplierForm activitySupplier = new SupplierForm();

            activitySupplier.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin1ActionPerformed
            AdminForm activityAdmin = new AdminForm();

            activityAdmin.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnAdmin1ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (!isValidInt(idBarang.getText())) {
            JOptionPane.showMessageDialog(null, "ID harus berupa angka.");
            return;
        }
        if (!isValidString(namaBarang.getText())) {
            JOptionPane.showMessageDialog(null, "Nama barang tidak boleh kosong.");
            return;
        }
        if (!isValidInt(hargaBarang.getText())) {
            JOptionPane.showMessageDialog(null, "Harga harus berupa angka.");
            return;
        }
        if (!isValidInt(jumlahBarang.getText())) {
            JOptionPane.showMessageDialog(null, "Stock harus berupa angka.");
            return;
        }
        try {
           
            String sql = "UPDATE tb_barang SET "
                    + "supplier_barang=" + "'" + supplierComboBox.getSelectedItem().toString() + "',"
                    + "nama_barang=" + "'" + namaBarang.getText() + "',"
                    + "kategori_barang=" + "'" + kategoriBarang.getSelectedItem().toString() + "',"
                    + "harga_barang=" + "'" + hargaBarang.getText() + "',"
                    + "stok_barang=" + "'" + jumlahBarang.getText() + "'"
                    + "WHERE id_barang=" + "'" + idBarang.getText() + "';";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Data berhasil di Edit");
            idBarang.setText("");
            namaBarang.setText("");
            hargaBarang.setText("");
            jumlahBarang.setText("");
            idBarang.setEnabled(true);
            idBarang.requestFocusInWindow();
            buka_tabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Proses edit gagal .. ");
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnProduk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduk1ActionPerformed
        ProdukForm activityProduk = new ProdukForm();

        activityProduk.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnProduk1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdukForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin1;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnProduk1;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JTextField hargaBarang;
    private javax.swing.JTextField idBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jumlahBarang;
    private javax.swing.JComboBox<String> kategoriBarang;
    private javax.swing.JTextField namaBarang;
    private javax.swing.JComboBox<String> supplierComboBox;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JScrollPane tableBarang;
    // End of variables declaration//GEN-END:variables


    private void buka_tabel() {
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("NO");
        model.addColumn("SUPLIER");
        model.addColumn("NAMA");
        model.addColumn("KATEGORI");
        model.addColumn("HARGA");
        model.addColumn("STOK");
        

        // menampilkan data kedalam jtable
        try {
            String sql = "select*from tb_barang";
           
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{res.getInt(1), res.getString(2),
                    res.getString(3),res.getString(4),res.getInt(5), res.getInt(6)});
            }
            tabelBarang.setModel(model);
        } catch (Exception e) {
        }
    }

    // Validation methods
    private boolean isValidInt(String input) {
        if (input == null || input.isEmpty()) {
            return false;
        }
        try {
            Integer.parseInt(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private boolean isValidString(String input) {
        return input != null && !input.trim().isEmpty();
    }

    
    //end 


    }

